### ISSUE TITLE
When to release codes?

### ISSUE THREAD

**Issue by jylovec** [wang-zidu/3DDFA-V3#1]
Wonderful job!!!I'd like to ask when you release codes and models?Thanks a lot.

**Comment by wang-zidu** [comment]
Thank you so much for your interest and support. I am currently busy with other submissions. I will release the code as soon as possible. Again, thank you for your patience and understanding!

**Comment by jylovec** [comment]
Thanks for your reply.And how about your synthetic face dataset.

**Comment by wang-zidu** [comment]
> Thanks for your reply.And how about your synthetic face dataset.

Certainly, the synthetic facial expression dataset will be released. Just a few days.

**Comment by wang-zidu** [comment]
> @wang-zidu Hey, any updates on this?

Thank you for your interest and patience. The initial release version is scheduled to be open-sourced no later than May 26th, and I'm working towards this goal.

**Comment by dio-Egypt** [comment]
练代码的实现。您有计划分享训练代码吗？

**Comment by dio-Egypt** [comment]
您有计划分享训练代码吗？

**Comment by zero0kiriyu** [comment]
> 您有计划分享训练代码吗？

建议不要等，大概率不会开源的，而且自己复现其实也不难

**Comment by dio-Egypt** [comment]
> > 您有计划分享训练代码吗？
> 
> 建议不要等，大概率不会开源，而且自己复现其实也不难

我看你之前也想复现，  你复现成功了吗老哥

**Comment by dio-Egypt** [comment]
> 且自己复现其实也不难

有偿指导一下
