### ISSUE TITLE
How to Export Materials（OBJ）

### ISSUE THREAD

**Issue by juntaosun** [wang-zidu/3DDFA-V3#13]
The generated OBJ models: _extractTex.obj and _pcaTex.obj, do not seem to carry UV material and texture attributes. How to export them? Can you update the relevant code? Thank you

**Comment by wang-zidu** [comment]
Thank you for your support. Actually, for convenience, I have stored the texture as vertex texture information. If you need to export texture attributes, please refer to [this](https://github.com/wang-zidu/3DDFA-V3/blob/36a63295d9b1949b32a4ce94a9097c3b97a124ca/model/recon.py#L534).

**Comment by rohit7044** [comment]
Hi, Thank you for this great project. I am also facing the same issue of extracting textureand slap it onto mesh. Can you explain how to do that?

**Comment by rohit7044** [comment]
Commenting out [this](https://github.com/wang-zidu/3DDFA-V3/blob/36a63295d9b1949b32a4ce94a9097c3b97a124ca/model/recon.py#L546) did the work. Thanks
